config/routes.rb
Grayherd::Application.routes.draw do
  require 'sub_domain.rb'
  #get "organizations/index"
  break if ARGV.join.include? 'assets:precompile'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints SubDomain do
    root :to => "organizations#show"
  end

  resources :seasons

  match "/sync/servertime" => "registrations#servertime", :via => [:get]

  resources :registrations

  resources :groups

  resources :people

  resources :organizations

  resources :export

  # root :to => 'organizations#index'

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :registrations
  has_many :groups
  belongs_to :organization

  def to_s
    "Season #{start}--#{self.end}"
  end

  def as_json(options={})
    { :name => name,
      :deadline => deadline,
      :start => start,
      :end => self.end,
      :id => 1,
      :organization => organization,
      :groups => groups}
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < SubDomainController
  # GET /seasons
  # GET /seasons.json
  def index

    respond_to do |format|
        format.html { redirect_to @organization }
    end
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
    @season = Season.find(params[:id])
    @groups = @season.groups.sort_by do |group|
      group[:name]
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @season }
    end
  end

  # GET /seasons/new
  # GET /seasons/new.json
  #def new
  #  @season = Season.new
  #
  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @season }
  #  end
  #end

  # GET /seasons/1/edit
  #def edit
  #  @season = Season.find(params[:id])
  #end

  # POST /seasons
  # POST /seasons.json
  #def create
  #  @season = Season.new(params[:season])
  #
  #  respond_to do |format|
  #    if @season.save
  #      format.html { redirect_to @season, notice: 'Season was successfully created.' }
  #      format.json { render json: @season, status: :created, location: @season }
  #    else
  #      format.html { render action: "new" }
  #      format.json { render json: @season.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /seasons/1
  # PUT /seasons/1.json
  #def update
  #  @season = Season.find(params[:id])
  #
  #  respond_to do |format|
  #    if @season.update_attributes(params[:season])
  #      format.html { redirect_to @season, notice: 'Season was successfully updated.' }
  #      format.json { head :ok }
  #    else
  #      format.html { render action: "edit" }
  #      format.json { render json: @season.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  #def destroy
  #  @season = Season.find(params[:id])
  #  @season.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to seasons_url }
  #    format.json { head :ok }
  #  end
  #end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :organization %><br />
    <%= f.collection_select :organization_id, Organization.all, :id, :name%>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= f.date_select :end %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.date_select :deadline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h1>Listing seasons</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><%= season.start %></td>
    <td><%= season.end %></td>
    <td><%= season.deadline %></td>
    <td><%= link_to 'Show', season %></td>
    <td><%= link_to 'Edit', edit_season_path(season) %></td>
    <td><%= link_to 'Destroy', season, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<% content_for :panel do %>
    <h5>Glöm inte att anmäla dig innan <%= @season.deadline %>!</h5>
    <p><%=  @season.organization.name %> använder anmälningstjänsten Greyherd</p>
    <p></p>
<% end %>

<% content_for :breadcrumbs do %>
   <li><%=link_to @season.organization.name, @season.organization  %></li>
    <li><span><%= @season.name %></span></li>
<% end %>

<p id="notice"><%= notice %></p>

<% if @season.organization_id == 1 %>
<img src="/images/svkh.png" width="300" height="58" alt="Svenska kyrkan Höllviken">
<% else %>
    <h3><%=  @season.organization.name %></h3>
<% end %>
<h1><%= @season.name %></h1>
<h2>Period <%= @season.start %>–<%= @season.end %></h2>

<p>
  <b>Deadline:</b>
  <%= @season.deadline %>
</p>

<h2>Grupper:</h2>

<ul>
<% @groups.each do |group| %>

    <li><%= link_to group.name, group %>,
      <% if group.remaining_seats? %>
      <%= group.remaining_tickets %> platser kvar
      <% elsif group.remaining_reserve_seats? %>

      <%= group.remaining_reserve_seats %> reservplatser kvar
          <%else%>
      alla platser upptagna
      <% end %>

          </li>

<% end %>
</ul>

<% if @season.organization_id == 1 %>
Vill du ställa dig i kö på en redan fulltecknad grupp, skicka ett mejl med alla uppgifter till <a href="mailto:ami.hall@svenskakyrkan.se">Ami Hall</a>.
<% end %>