config/routes.rb
Grayherd::Application.routes.draw do
  require 'sub_domain.rb'
  #get "organizations/index"
  break if ARGV.join.include? 'assets:precompile'
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  constraints SubDomain do
    root :to => "organizations#show"
  end

  resources :seasons

  match "/sync/servertime" => "registrations#servertime", :via => [:get]

  resources :registrations

  resources :groups

  resources :people

  resources :organizations

  resources :export

  # root :to => 'organizations#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :registrations
  has_many :registration_tickets
  belongs_to :season

  def first_ticket_expire
    registration_tickets.where("updated_at > ?", DateTime.now - RegistrationTicket::TICKET_TIMEOUT.minutes)
        .order(:updated_at).take.updated_at + + RegistrationTicket::TICKET_TIMEOUT.minutes
  end

  def minutes_left
    ((first_ticket_expire - DateTime.now) / 60).ceil
  end

  def outstanding_tickets
    #only count valid tickets
    registration_tickets.where("updated_at > ?", DateTime.now - RegistrationTicket::TICKET_TIMEOUT.minutes).count
  end

  def remaining_tickets
    diff = remaining_seats - outstanding_tickets
    diff < 0 ? 0 : diff
  end

  def remaining_seats
    if remaining_seats?
     capacity - registrations.count
    else
      0
    end
  end

  def remaining_seats?
    registrations.count < capacity
  end

  def remaining_reserve_seats?
    extra_capacity_num = extra_capacity.nil? ? 0 : extra_capacity # temp fix since
    !remaining_seats? && (extra_capacity_num + capacity) > registrations.count
  end

  def remaining_reserve_seats
    extra_capacity_num = extra_capacity.nil? ? 0 : extra_capacity
    if remaining_reserve_seats?
      (extra_capacity_num + capacity) - registrations.count
    else
      if remaining_seats?
        false
      else
        0
      end
    end
  end

  def no_seats_left?
    !(remaining_seats? || remaining_reserve_seats?)
  end

  def get_ticket(session_id)
    puts "Get registration ticket for session id #{session_id}"
    rts = RegistrationTicket.where("session_id = ? AND group_id = ?", session_id, id)
    if rts.size > 0
      puts "Found existing ticket"
      rt = rts.first
      if rt.still_valid?
        puts "RT valid"
        # save registration
      else
        puts "RT invalid"
        # renegotiate registration ticket
        if rt.renegotiate
          puts "Renegotiated ticket successfully"
        else
          puts "Couldn't renegotiate ticket."
          rt = false
        end
      end
      rt
    else
      puts "No existing ticket"
      if remaining_tickets > 0
        puts "Create new ticket"
        rt = RegistrationTicket.new({session_id: session_id})
        rt.group_id = id
        rt.save
        rt
      else
        puts "No remaining tickets left."
        rt = false
      end
      rt
    end
  end

  def as_json(options={})
    { name: name,
      capacity: capacity,
      description: description,
      extra_capacity: extra_capacity,
      id: id,
      mail_message: mail_message,
      season_id: season_id,
      sender_address: sender_address,
      sender_email: sender_email,
      url: url,
      remaining_seats: remaining_seats,
      remaining_reserve_seats: remaining_reserve_seats,
      registrations: registrations
    }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @groups.each do |group| %>
  <tr>
    <td><%= group.name %></td>
    <td><%= link_to 'Show', group %></td>
  </tr>
<% end %>
</table>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<% content_for :breadcrumbs do %>
   <li><%=link_to @group.season.organization.name, @group.season.organization  %></li>
    <li><%=link_to @group.season.name, @group.season%></li>
    <li><span><%= @group.name %></span></li>
<% end %>

<% content_for :panel do %>
    <h5>Välkommen att anmäla dig till <%= @group.name %>!</h5>
    <p>Tänk på att anmälningstiden går ut <%= @group.season.deadline %></p>
<% end %>


<% if @group.remaining_reserve_seats? %>
<% content_for :notice do %>
    <p>Det finns <%= @group.remaining_reserve_seats %> reservplatser kvar</p>
<% end %>
<% end %>

<% if @group.no_seats_left? %>
<% content_for :notice do %>
    <p>Det finns inga platser kvar</p>
<% end %>
<% end %>


<% if @group.season.organization_id == 1 %>
    <img src="/images/svkh.png" width="300" height="58" alt="Svenska kyrkan Höllviken">
<% else %>
    <h1><%= @group.season.organization.name %></h1>
<% end %>

<h2>Period <%= @group.season.start %>–<%= @group.season.end %></h2>

<h3><%= @group.name %></h3>


<p>
  <b>Beskrivning:</b>
  <%=  simple_format(@group.description) %>
</p>

<p>
  <b>Antal platser:</b>
  <%= @group.capacity %>
</p>


<p><%= @group.registrations.count %> deltagare registrerade
(<%= @group.outstanding_tickets %> personer håller på att fylla i registreringsformulär)
</p>

<% if @group.remaining_seats? %>
<p>
  <b>Antal lediga platser:</b>
  <%= @group.remaining_tickets %> platser kvar
</p>
<% end %>

<% if @group.remaining_reserve_seats? %>
<p>
  <b>Antal lediga platser:</b>
  Alla ordinarie platser är upptagna.
</p>
<% end %>

<% if @group.no_seats_left? %>
<p>
  <b>Antal lediga platser:</b>
  Alla platser är upptagna.
</p>
<% end %>

<%unless @group.no_seats_left?%>
    <% unless @group.remaining_tickets == 0 %>
        <a href="<%= new_registration_path(:group => @group.id)%>" class="nice radius green button">Registrera dig</a>
    <% end %>
    <% if @group.remaining_tickets == 0 %>
        <b>Alla platser är just nu reserverade.</b> Dock kan det bli platser över i fall personer med reservationer inte fullföljer
        sina registreringar.
    <%end%>
<%end%>